### PR TITLE
Updates for building in CI/CD and for PRs

### PR DESCRIPTION
**Pull request by mikesalvia**

### CODE REVIEW

**Comment by mikesalvia** [comment]
test this please

**Comment by jwsdkleads** [comment]
Tests have PASSED :white_check_mark:

https://jenkins-sdk.longtailvideo.com/job/jwplayer-android-sdk-best-practice-apps-pr/2/

**Comment by jwsdkleads** [comment]
Tests have PASSED :white_check_mark:

https://jenkins-sdk.longtailvideo.com/job/jwplayer-android-sdk-best-practice-apps-pr/3/

**Comment by jwsdkleads** [comment]
Tests have PASSED :white_check_mark:

https://jenkins-sdk.longtailvideo.com/job/jwplayer-android-sdk-best-practice-apps-pr/4/

**Comment by jwsdkleads** [comment]
Tests have PASSED :white_check_mark:

https://jenkins-sdk.longtailvideo.com/job/jwplayer-android-sdk-best-practice-apps-pr/5/

**Review by guitarsforever — APPROVED** [review]
LGTM

**Pull request merged**
