### PR TITLE
AndroidX compatibility

### PR DESCRIPTION
**Pull request by mikesalvia**

### CODE REVIEW

**Comment by jwsdkleads** [comment]
Tests have FAILED :poop:

https://jenkins-sdk.longtailvideo.com/job/jwplayer-android-sdk-best-practice-apps-pr/56/

**Comment by jwsdkleads** [comment]
Tests have FAILED :poop:

https://jenkins-sdk.longtailvideo.com/job/jwplayer-android-sdk-best-practice-apps-pr/58/

**Comment by jwsdkleads** [comment]
Tests have FAILED :poop:

https://jenkins-sdk.longtailvideo.com/job/jwplayer-android-sdk-best-practice-apps-pr/60/

**Comment by jwsdkleads** [comment]
Tests have PASSED :white_check_mark:

https://jenkins-sdk.longtailvideo.com/job/jwplayer-android-sdk-best-practice-apps-pr/127/

**Comment by jwsdkleads** [comment]
Tests have PASSED :white_check_mark:

https://jenkins-sdk.longtailvideo.com/job/jwplayer-android-sdk-best-practice-apps-pr/128/

**Review by GMSyrimis — APPROVED** [review]

**Review by paulmandal — APPROVED** [review]
LGTM

**Pull request merged**
